/**
 * The shipped company catalog.
 *
 * Every row here was verified against the live board before it was written down: the probe
 * hit the endpoint, confirmed it answered, and confirmed it returned real postings. A few
 * plausible-looking slugs (icon, method, sila, mosaic) turned out to belong to a different
 * company with the same word for a name, so they were dropped rather than shipped wrong.
 *
 * This list is a starting point, not the product. The real coverage story is the "add any
 * company" box: paste a Greenhouse, Lever, Ashby, SmartRecruiters, Workable, or Recruitee
 * careers URL and Jobwatch works out the rest. Roughly half of all companies run one of
 * these six boards, and none of them require a key.
 */

import type { AtsKind, Source } from "./types";

export interface PackDef {
  id: string;
  label: string;
  blurb: string;
}

/** Groupings the picker offers. A company belongs to exactly one, purely for browsing. */
export const PACKS: PackDef[] = [
  { id: "software", label: "Software & Product", blurb: "Product companies hiring engineers, PMs, and designers." },
  { id: "ai", label: "AI & ML", blurb: "Labs and applied-AI companies." },
  { id: "data", label: "Data & Infrastructure", blurb: "Data platforms, observability, and developer infrastructure." },
  { id: "design", label: "Design", blurb: "Design tools, studios, and agencies with public job boards." },
  { id: "finance", label: "Finance & Fintech", blurb: "Banks, asset managers, payments, and financial infrastructure." },
  { id: "health", label: "Health & Bio", blurb: "Care delivery, digital health, pharma, and medical devices." },
  { id: "education", label: "Education", blurb: "Universities, schools, and education technology." },
  { id: "nonprofit", label: "Nonprofit & Civic", blurb: "Mission-driven organizations and public-interest tech." },
  { id: "publicsector", label: "Government & Public Sector", blurb: "Public agencies, civic tech, and government contractors." },
  { id: "retail", label: "Retail & Consumer", blurb: "Consumer brands, ecommerce, food, and retailers." },
  { id: "hospitality", label: "Hospitality & Travel", blurb: "Hotels, restaurants, airlines, and travel." },
  { id: "media", label: "Media & Creator", blurb: "Publishers, streaming, gaming, and creator platforms." },
  { id: "marketing", label: "Marketing & Growth", blurb: "Marketing platforms, agencies, and growth-heavy teams." },
  { id: "realestate", label: "Real Estate & Property", blurb: "Brokerages, property tech, and development." },
  { id: "aec", label: "Architecture & Construction", blurb: "Construction tech, engineering firms, and building products." },
  { id: "industrial", label: "Industrial & Manufacturing", blurb: "Manufacturing, logistics, supply chain, and materials." },
  { id: "hardware", label: "Hardware & Robotics", blurb: "Physical products, robotics, aerospace, and vehicles." },
  { id: "climate", label: "Climate & Energy", blurb: "Energy, decarbonization, and sustainability." },
  { id: "professional", label: "Professional Services", blurb: "Consulting, legal, accounting, HR, and recruiting." },
];

interface CatalogRow {
  kind: AtsKind;
  token: string;
  name: string;
  pack: string;
}

const CATALOG: CatalogRow[] = [

  // Software & Product (51)
  { kind: "greenhouse", token: "affirm", name: "Affirm", pack: "software" },
  { kind: "greenhouse", token: "airbnb", name: "Airbnb", pack: "software" },
  { kind: "greenhouse", token: "asana", name: "Asana", pack: "software" },
  { kind: "ashby", token: "benchling", name: "Benchling", pack: "software" },
  { kind: "greenhouse", token: "brex", name: "Brex", pack: "software" },
  { kind: "greenhouse", token: "calendly", name: "Calendly", pack: "software" },
  { kind: "greenhouse", token: "chime", name: "Chime", pack: "software" },
  { kind: "greenhouse", token: "cloudflare", name: "Cloudflare", pack: "software" },
  { kind: "greenhouse", token: "coinbase", name: "Coinbase", pack: "software" },
  { kind: "greenhouse", token: "discord", name: "Discord", pack: "software" },
  { kind: "greenhouse", token: "doordashusa", name: "DoorDash", pack: "software" },
  { kind: "greenhouse", token: "dropbox", name: "Dropbox", pack: "software" },
  { kind: "greenhouse", token: "duolingo", name: "Duolingo", pack: "software" },
  { kind: "greenhouse", token: "epicgames", name: "Epic Games", pack: "software" },
  { kind: "greenhouse", token: "figma", name: "Figma", pack: "software" },
  { kind: "greenhouse", token: "forter", name: "Forter", pack: "software" },
  { kind: "greenhouse", token: "gitlab", name: "GitLab", pack: "software" },
  { kind: "greenhouse", token: "gongio", name: "Gong", pack: "software" },
  { kind: "greenhouse", token: "gusto", name: "Gusto", pack: "software" },
  { kind: "greenhouse", token: "instacart", name: "Instacart", pack: "software" },
  { kind: "greenhouse", token: "intercom", name: "Fin (formerly Intercom)", pack: "software" },
  { kind: "greenhouse", token: "jfrog", name: "JFrog", pack: "software" },
  { kind: "greenhouse", token: "lightricks", name: "Lightricks", pack: "software" },
  { kind: "ashby", token: "linear", name: "Linear", pack: "software" },
  { kind: "greenhouse", token: "lyft", name: "Lyft", pack: "software" },
  { kind: "greenhouse", token: "monzo", name: "Monzo", pack: "software" },
  { kind: "greenhouse", token: "netlify", name: "Netlify", pack: "software" },
  { kind: "ashby", token: "notion", name: "Notion", pack: "software" },
  { kind: "lever", token: "outreach", name: "Outreach", pack: "software" },
  { kind: "greenhouse", token: "peloton", name: "Peloton", pack: "software" },
  { kind: "greenhouse", token: "pinterest", name: "Pinterest", pack: "software" },
  { kind: "lever", token: "pipedrive", name: "Pipedrive", pack: "software" },
  { kind: "ashby", token: "plaid", name: "Plaid", pack: "software" },
  { kind: "greenhouse", token: "postman", name: "Postman", pack: "software" },
  { kind: "ashby", token: "ramp", name: "Ramp", pack: "software" },
  { kind: "greenhouse", token: "reddit", name: "Reddit", pack: "software" },
  { kind: "greenhouse", token: "riotgames", name: "Riot Games", pack: "software" },
  { kind: "greenhouse", token: "riskified", name: "Riskified", pack: "software" },
  { kind: "greenhouse", token: "robinhood", name: "Robinhood", pack: "software" },
  { kind: "greenhouse", token: "roblox", name: "Roblox", pack: "software" },
  { kind: "greenhouse", token: "samsara", name: "Samsara", pack: "software" },
  { kind: "ashby", token: "sentry", name: "Sentry", pack: "software" },
  { kind: "greenhouse", token: "smartsheet", name: "Smartsheet", pack: "software" },
  { kind: "lever", token: "spotify", name: "Spotify", pack: "software" },
  { kind: "greenhouse", token: "squarespace", name: "Squarespace", pack: "software" },
  { kind: "greenhouse", token: "stripe", name: "Stripe", pack: "software" },
  { kind: "greenhouse", token: "twilio", name: "Twilio", pack: "software" },
  { kind: "greenhouse", token: "vercel", name: "Vercel", pack: "software" },
  { kind: "lever", token: "wealthfront", name: "Wealthfront", pack: "software" },
  { kind: "greenhouse", token: "webflow", name: "Webflow", pack: "software" },
  { kind: "ashby", token: "zapier", name: "Zapier", pack: "software" },

  // AI & ML (41)
  { kind: "ashby", token: "abridge", name: "Abridge", pack: "ai" },
  { kind: "greenhouse", token: "anthropic", name: "Anthropic", pack: "ai" },
  { kind: "ashby", token: "anyscale", name: "Anyscale", pack: "ai" },
  { kind: "greenhouse", token: "assemblyai", name: "AssemblyAI", pack: "ai" },
  { kind: "ashby", token: "baseten", name: "Baseten", pack: "ai" },
  { kind: "greenhouse", token: "blackforestlabs", name: "Black Forest Labs", pack: "ai" },
  { kind: "ashby", token: "character", name: "Character.AI", pack: "ai" },
  { kind: "ashby", token: "cognition", name: "Cognition", pack: "ai" },
  { kind: "ashby", token: "cohere", name: "Cohere", pack: "ai" },
  { kind: "greenhouse", token: "coreweave", name: "CoreWeave", pack: "ai" },
  { kind: "greenhouse", token: "cresta", name: "Cresta", pack: "ai" },
  { kind: "ashby", token: "cursor", name: "Cursor", pack: "ai" },
  { kind: "ashby", token: "decagon", name: "Decagon", pack: "ai" },
  { kind: "ashby", token: "deepgram", name: "Deepgram", pack: "ai" },
  { kind: "greenhouse", token: "descript", name: "Descript", pack: "ai" },
  { kind: "ashby", token: "elevenlabs", name: "ElevenLabs", pack: "ai" },
  { kind: "ashby", token: "fireworksai", name: "Fireworks AI", pack: "ai" },
  { kind: "greenhouse", token: "gleanwork", name: "Glean", pack: "ai" },
  { kind: "ashby", token: "harvey", name: "Harvey", pack: "ai" },
  { kind: "greenhouse", token: "heygen", name: "HeyGen", pack: "ai" },
  { kind: "greenhouse", token: "humeai", name: "Hume AI", pack: "ai" },
  { kind: "ashby", token: "lambda", name: "Lambda", pack: "ai" },
  { kind: "ashby", token: "langchain", name: "LangChain", pack: "ai" },
  { kind: "ashby", token: "modal", name: "Modal", pack: "ai" },
  { kind: "greenhouse", token: "nebius", name: "Nebius", pack: "ai" },
  { kind: "greenhouse", token: "observeai", name: "Observe.AI", pack: "ai" },
  { kind: "ashby", token: "openai", name: "OpenAI", pack: "ai" },
  { kind: "greenhouse", token: "parloa", name: "Parloa", pack: "ai" },
  { kind: "ashby", token: "perplexity", name: "Perplexity", pack: "ai" },
  { kind: "ashby", token: "pika", name: "Pika", pack: "ai" },
  { kind: "greenhouse", token: "polyai", name: "PolyAI", pack: "ai" },
  { kind: "ashby", token: "poolside", name: "Poolside", pack: "ai" },
  { kind: "ashby", token: "runway", name: "Runway", pack: "ai" },
  { kind: "greenhouse", token: "scaleai", name: "Scale AI", pack: "ai" },
  { kind: "ashby", token: "sierra", name: "Sierra", pack: "ai" },
  { kind: "greenhouse", token: "speechmatics", name: "Speechmatics", pack: "ai" },
  { kind: "greenhouse", token: "stabilityai", name: "Stability AI", pack: "ai" },
  { kind: "ashby", token: "suno", name: "Suno", pack: "ai" },
  { kind: "ashby", token: "synthesia", name: "Synthesia", pack: "ai" },
  { kind: "greenhouse", token: "togetherai", name: "Together AI", pack: "ai" },
  { kind: "ashby", token: "writer", name: "Writer", pack: "ai" },

  // Data & Infrastructure (36)
  { kind: "ashby", token: "airbyte", name: "Airbyte", pack: "data" },
  { kind: "greenhouse", token: "airtable", name: "Airtable", pack: "data" },
  { kind: "greenhouse", token: "amplitude", name: "Amplitude", pack: "data" },
  { kind: "ashby", token: "astronomer", name: "Astronomer", pack: "data" },
  { kind: "greenhouse", token: "chainguard", name: "Chainguard", pack: "data" },
  { kind: "greenhouse", token: "clickhouse", name: "ClickHouse", pack: "data" },
  { kind: "greenhouse", token: "cockroachlabs", name: "Cockroach Labs", pack: "data" },
  { kind: "ashby", token: "confluent", name: "Confluent", pack: "data" },
  { kind: "greenhouse", token: "dashlane", name: "Dashlane", pack: "data" },
  { kind: "greenhouse", token: "databricks", name: "Databricks", pack: "data" },
  { kind: "greenhouse", token: "datadog", name: "Datadog", pack: "data" },
  { kind: "ashby", token: "drata", name: "Drata", pack: "data" },
  { kind: "greenhouse", token: "dremio", name: "Dremio", pack: "data" },
  { kind: "greenhouse", token: "elastic", name: "Elastic", pack: "data" },
  { kind: "greenhouse", token: "fivetran", name: "Fivetran", pack: "data" },
  { kind: "greenhouse", token: "grafanalabs", name: "Grafana Labs", pack: "data" },
  { kind: "greenhouse", token: "hextechnologies", name: "Hex", pack: "data" },
  { kind: "greenhouse", token: "hightouch", name: "Hightouch", pack: "data" },
  { kind: "greenhouse", token: "launchdarkly", name: "LaunchDarkly", pack: "data" },
  { kind: "ashby", token: "materialize", name: "Materialize", pack: "data" },
  { kind: "lever", token: "metabase", name: "Metabase", pack: "data" },
  { kind: "greenhouse", token: "mixpanel", name: "Mixpanel", pack: "data" },
  { kind: "greenhouse", token: "mongodb", name: "MongoDB", pack: "data" },
  { kind: "ashby", token: "posthog", name: "PostHog", pack: "data" },
  { kind: "ashby", token: "prefect", name: "Prefect", pack: "data" },
  { kind: "ashby", token: "railway", name: "Railway", pack: "data" },
  { kind: "ashby", token: "render", name: "Render", pack: "data" },
  { kind: "ashby", token: "semgrep", name: "Semgrep", pack: "data" },
  { kind: "greenhouse", token: "sigmacomputing", name: "Sigma Computing", pack: "data" },
  { kind: "ashby", token: "snowflake", name: "Snowflake", pack: "data" },
  { kind: "greenhouse", token: "starburst", name: "Starburst", pack: "data" },
  { kind: "ashby", token: "supabase", name: "Supabase", pack: "data" },
  { kind: "lever", token: "sysdig", name: "Sysdig", pack: "data" },
  { kind: "greenhouse", token: "tailscale", name: "Tailscale", pack: "data" },
  { kind: "ashby", token: "temporal", name: "Temporal", pack: "data" },
  { kind: "ashby", token: "vanta", name: "Vanta", pack: "data" },

  // Design (16)
  { kind: "greenhouse", token: "akqa", name: "AKQA", pack: "design" },
  { kind: "smartrecruiters", token: "canva", name: "Canva", pack: "design" },
  { kind: "greenhouse", token: "dept", name: "DEPT", pack: "design" },
  { kind: "lever", token: "gettyimages", name: "Getty Images", pack: "design" },
  { kind: "greenhouse", token: "hugeinc", name: "Huge", pack: "design" },
  { kind: "greenhouse", token: "ideo", name: "IDEO", pack: "design" },
  { kind: "lever", token: "instrument", name: "Instrument", pack: "design" },
  { kind: "ashby", token: "kittl", name: "Kittl", pack: "design" },
  { kind: "greenhouse", token: "mapprojectoffice", name: "Map Project Office", pack: "design" },
  { kind: "greenhouse", token: "monks", name: "Media.Monks", pack: "design" },
  { kind: "greenhouse", token: "metalab", name: "MetaLab", pack: "design" },
  { kind: "ashby", token: "miro", name: "Miro", pack: "design" },
  { kind: "ashby", token: "photoroom", name: "Photoroom", pack: "design" },
  { kind: "greenhouse", token: "rga", name: "R/GA", pack: "design" },
  { kind: "ashby", token: "recraft", name: "Recraft", pack: "design" },
  { kind: "lever", token: "superside", name: "Superside", pack: "design" },

  // Finance & Fintech (39)
  { kind: "greenhouse", token: "adyen", name: "Adyen", pack: "finance" },
  { kind: "greenhouse", token: "akunacapital", name: "Akuna Capital", pack: "finance" },
  { kind: "greenhouse", token: "alloy", name: "Alloy", pack: "finance" },
  { kind: "greenhouse", token: "alphasense", name: "AlphaSense", pack: "finance" },
  { kind: "lever", token: "anchorage", name: "Anchorage Digital", pack: "finance" },
  { kind: "greenhouse", token: "aqr", name: "AQR Capital", pack: "finance" },
  { kind: "lever", token: "belvederetrading", name: "Belvedere Trading", pack: "finance" },
  { kind: "greenhouse", token: "betterment", name: "Betterment", pack: "finance" },
  { kind: "recruitee", token: "bunq", name: "Bunq", pack: "finance" },
  { kind: "greenhouse", token: "carta", name: "Carta", pack: "finance" },
  { kind: "greenhouse", token: "coalition", name: "Coalition", pack: "finance" },
  { kind: "greenhouse", token: "ethoslife", name: "Ethos", pack: "finance" },
  { kind: "greenhouse", token: "fireblocks", name: "Fireblocks", pack: "finance" },
  { kind: "greenhouse", token: "flowtraders", name: "Flow Traders", pack: "finance" },
  { kind: "greenhouse", token: "gemini", name: "Gemini", pack: "finance" },
  { kind: "greenhouse", token: "imc", name: "IMC Trading", pack: "finance" },
  { kind: "greenhouse", token: "janestreet", name: "Jane Street", pack: "finance" },
  { kind: "greenhouse", token: "jumptrading", name: "Jump Trading", pack: "finance" },
  { kind: "ashby", token: "lemonade", name: "Lemonade", pack: "finance" },
  { kind: "greenhouse", token: "mangroup", name: "Man Group", pack: "finance" },
  { kind: "greenhouse", token: "marqeta", name: "Marqeta", pack: "finance" },
  { kind: "greenhouse", token: "mercury", name: "Mercury", pack: "finance" },
  { kind: "ashby", token: "moderntreasury", name: "Modern Treasury", pack: "finance" },
  { kind: "ashby", token: "mollie", name: "Mollie", pack: "finance" },
  { kind: "greenhouse", token: "n26", name: "N26", pack: "finance" },
  { kind: "greenhouse", token: "oldmissioncapital", name: "Old Mission Capital", pack: "finance" },
  { kind: "greenhouse", token: "openly", name: "Openly", pack: "finance" },
  { kind: "greenhouse", token: "payoneer", name: "Payoneer", pack: "finance" },
  { kind: "ashby", token: "pennylane", name: "Pennylane", pack: "finance" },
  { kind: "greenhouse", token: "pieinsurance", name: "Pie Insurance", pack: "finance" },
  { kind: "greenhouse", token: "point72", name: "Point72", pack: "finance" },
  { kind: "lever", token: "qonto", name: "Qonto", pack: "finance" },
  { kind: "greenhouse", token: "squarepointcapital", name: "Squarepoint Capital", pack: "finance" },
  { kind: "greenhouse", token: "sumup", name: "SumUp", pack: "finance" },
  { kind: "greenhouse", token: "tide", name: "Tide", pack: "finance" },
  { kind: "greenhouse", token: "towerresearchcapital", name: "Tower Research Capital", pack: "finance" },
  { kind: "ashby", token: "unit", name: "Unit", pack: "finance" },
  { kind: "smartrecruiters", token: "wise", name: "Wise", pack: "finance" },
  { kind: "lever", token: "zopa", name: "Zopa", pack: "finance" },

  // Health & Bio (38)
  { kind: "greenhouse", token: "10xgenomics", name: "10x Genomics", pack: "health" },
  { kind: "lever", token: "aledade", name: "Aledade", pack: "health" },
  { kind: "greenhouse", token: "beamtherapeutics", name: "Beam Therapeutics", pack: "health" },
  { kind: "greenhouse", token: "bicyclehealth", name: "Bicycle Health", pack: "health" },
  { kind: "ashby", token: "cedar", name: "Cedar", pack: "health" },
  { kind: "greenhouse", token: "colossalbiosciences", name: "Colossal Biosciences", pack: "health" },
  { kind: "greenhouse", token: "curative", name: "Curative", pack: "health" },
  { kind: "greenhouse", token: "doctolib", name: "Doctolib", pack: "health" },
  { kind: "greenhouse", token: "doximity", name: "Doximity", pack: "health" },
  { kind: "smartrecruiters", token: "eurofins", name: "Eurofins", pack: "health" },
  { kind: "greenhouse", token: "flatironhealth", name: "Flatiron Health", pack: "health" },
  { kind: "greenhouse", token: "freenome", name: "Freenome", pack: "health" },
  { kind: "greenhouse", token: "generatebiomedicines", name: "Generate Biomedicines", pack: "health" },
  { kind: "greenhouse", token: "ginkgobioworks", name: "Ginkgo Bioworks", pack: "health" },
  { kind: "lever", token: "grailbio", name: "Grail", pack: "health" },
  { kind: "ashby", token: "headway", name: "Headway", pack: "health" },
  { kind: "lever", token: "includedhealth", name: "Included Health", pack: "health" },
  { kind: "ashby", token: "insitro", name: "Insitro", pack: "health" },
  { kind: "smartrecruiters", token: "intuitive", name: "Intuitive Surgical", pack: "health" },
  { kind: "greenhouse", token: "isomorphiclabs", name: "Isomorphic Labs", pack: "health" },
  { kind: "greenhouse", token: "komodohealth", name: "Komodo Health", pack: "health" },
  { kind: "lever", token: "lyrahealth", name: "Lyra Health", pack: "health" },
  { kind: "greenhouse", token: "mavenclinic", name: "Maven Clinic", pack: "health" },
  { kind: "greenhouse", token: "natera", name: "Natera", pack: "health" },
  { kind: "greenhouse", token: "usenourish", name: "Nourish", pack: "health" },
  { kind: "greenhouse", token: "omadahealth", name: "Omada Health", pack: "health" },
  { kind: "greenhouse", token: "onemedical", name: "One Medical", pack: "health" },
  { kind: "greenhouse", token: "ophelia", name: "Ophelia", pack: "health" },
  { kind: "greenhouse", token: "papa", name: "Papa", pack: "health" },
  { kind: "greenhouse", token: "parsleyhealth", name: "Parsley Health", pack: "health" },
  { kind: "greenhouse", token: "recursionpharmaceuticals", name: "Recursion", pack: "health" },
  { kind: "lever", token: "ro", name: "Ro", pack: "health" },
  { kind: "lever", token: "swordhealth", name: "Sword Health", pack: "health" },
  { kind: "greenhouse", token: "talkspace", name: "Talkspace", pack: "health" },
  { kind: "greenhouse", token: "truveta", name: "Truveta", pack: "health" },
  { kind: "lever", token: "veeva", name: "Veeva Systems", pack: "health" },
  { kind: "greenhouse", token: "wellthy", name: "Wellthy", pack: "health" },
  { kind: "greenhouse", token: "zocdoc", name: "Zocdoc", pack: "health" },

  // Education (16)
  { kind: "ashby", token: "babbel", name: "Babbel", pack: "education" },
  { kind: "ashby", token: "classdojo", name: "ClassDojo", pack: "education" },
  { kind: "greenhouse", token: "coursera", name: "Coursera", pack: "education" },
  { kind: "greenhouse", token: "datacamp", name: "DataCamp", pack: "education" },
  { kind: "greenhouse", token: "generalassembly", name: "General Assembly", pack: "education" },
  { kind: "greenhouse", token: "guild", name: "Guild Education", pack: "education" },
  { kind: "ashby", token: "handshake", name: "Handshake", pack: "education" },
  { kind: "smartrecruiters", token: "instructure", name: "Instructure", pack: "education" },
  { kind: "greenhouse", token: "masterclass", name: "MasterClass", pack: "education" },
  { kind: "ashby", token: "multiverse", name: "Multiverse", pack: "education" },
  { kind: "greenhouse", token: "newsela", name: "Newsela", pack: "education" },
  { kind: "greenhouse", token: "outschool", name: "Outschool", pack: "education" },
  { kind: "ashby", token: "preply", name: "Preply", pack: "education" },
  { kind: "greenhouse", token: "springboard", name: "Springboard", pack: "education" },
  { kind: "greenhouse", token: "udacity", name: "Udacity", pack: "education" },
  { kind: "greenhouse", token: "udemy", name: "Udemy", pack: "education" },

  // Nonprofit & Civic (20)
  { kind: "greenhouse", token: "aclu", name: "ACLU", pack: "nonprofit" },
  { kind: "greenhouse", token: "acumen", name: "Acumen", pack: "nonprofit" },
  { kind: "lever", token: "ashoka", name: "Ashoka", pack: "nonprofit" },
  { kind: "greenhouse", token: "breakthroughenergy", name: "Breakthrough Energy", pack: "nonprofit" },
  { kind: "greenhouse", token: "chanzuckerberginitiative", name: "Chan Zuckerberg Initiative", pack: "nonprofit" },
  { kind: "lever", token: "charitywater", name: "Charity Water", pack: "nonprofit" },
  { kind: "greenhouse", token: "codeforamerica", name: "Code for America", pack: "nonprofit" },
  { kind: "recruitee", token: "msf", name: "Doctors Without Borders", pack: "nonprofit" },
  { kind: "greenhouse", token: "donorschoose", name: "DonorsChoose", pack: "nonprofit" },
  { kind: "lever", token: "girlswhocode", name: "Girls Who Code", pack: "nonprofit" },
  { kind: "greenhouse", token: "givedirectly", name: "GiveDirectly", pack: "nonprofit" },
  { kind: "greenhouse", token: "givewell", name: "GiveWell", pack: "nonprofit" },
  { kind: "greenhouse", token: "greenpeace", name: "Greenpeace", pack: "nonprofit" },
  { kind: "greenhouse", token: "humanrightswatch", name: "Human Rights Watch", pack: "nonprofit" },
  { kind: "greenhouse", token: "khanacademy", name: "Khan Academy", pack: "nonprofit" },
  { kind: "greenhouse", token: "mozilla", name: "Mozilla", pack: "nonprofit" },
  { kind: "greenhouse", token: "oneacrefund", name: "One Acre Fund", pack: "nonprofit" },
  { kind: "lever", token: "sierraclub", name: "Sierra Club", pack: "nonprofit" },
  { kind: "lever", token: "thetrevorproject", name: "The Trevor Project", pack: "nonprofit" },
  { kind: "greenhouse", token: "wikimedia", name: "Wikimedia Foundation", pack: "nonprofit" },

  // Government & Public Sector (13)
  { kind: "greenhouse", token: "andurilindustries", name: "Anduril", pack: "publicsector" },
  { kind: "greenhouse", token: "astranis", name: "Astranis", pack: "publicsector" },
  { kind: "smartrecruiters", token: "caci", name: "CACI", pack: "publicsector" },
  { kind: "greenhouse", token: "epirus", name: "Epirus", pack: "publicsector" },
  { kind: "greenhouse", token: "esri", name: "Esri", pack: "publicsector" },
  { kind: "greenhouse", token: "mark43", name: "Mark43", pack: "publicsector" },
  { kind: "greenhouse", token: "navapbc", name: "Nava PBC", pack: "publicsector" },
  { kind: "lever", token: "palantir", name: "Palantir", pack: "publicsector" },
  { kind: "greenhouse", token: "planetlabs", name: "Planet Labs", pack: "publicsector" },
  { kind: "greenhouse", token: "rocketlab", name: "Rocket Lab", pack: "publicsector" },
  { kind: "lever", token: "shieldai", name: "Shield AI", pack: "publicsector" },
  { kind: "greenhouse", token: "vardaspace", name: "Varda Space", pack: "publicsector" },
  { kind: "greenhouse", token: "flyzipline", name: "Zipline", pack: "publicsector" },

  // Retail & Consumer (20)
  { kind: "greenhouse", token: "ag1", name: "AG1", pack: "retail" },
  { kind: "smartrecruiters", token: "asos", name: "ASOS", pack: "retail" },
  { kind: "greenhouse", token: "bombas", name: "Bombas", pack: "retail" },
  { kind: "greenhouse", token: "brilliantearth", name: "Brilliant Earth", pack: "retail" },
  { kind: "greenhouse", token: "everlane", name: "Everlane", pack: "retail" },
  { kind: "greenhouse", token: "faire", name: "Faire", pack: "retail" },
  { kind: "greenhouse", token: "glossier", name: "Glossier", pack: "retail" },
  { kind: "greenhouse", token: "goatgroup", name: "GOAT Group", pack: "retail" },
  { kind: "greenhouse", token: "gymshark", name: "Gymshark", pack: "retail" },
  { kind: "greenhouse", token: "mejuri", name: "Mejuri", pack: "retail" },
  { kind: "greenhouse", token: "ocadogroup", name: "Ocado", pack: "retail" },
  { kind: "greenhouse", token: "olipop", name: "Olipop", pack: "retail" },
  { kind: "greenhouse", token: "onrunning", name: "On", pack: "retail" },
  { kind: "greenhouse", token: "parachutehome", name: "Parachute Home", pack: "retail" },
  { kind: "greenhouse", token: "quince", name: "Quince", pack: "retail" },
  { kind: "greenhouse", token: "reformation", name: "Reformation", pack: "retail" },
  { kind: "greenhouse", token: "renttherunway", name: "Rent the Runway", pack: "retail" },
  { kind: "greenhouse", token: "ruggable", name: "Ruggable", pack: "retail" },
  { kind: "greenhouse", token: "stockx", name: "StockX", pack: "retail" },
  { kind: "greenhouse", token: "vitalfarms", name: "Vital Farms", pack: "retail" },

  // Hospitality & Travel (15)
  { kind: "smartrecruiters", token: "accor", name: "Accor", pack: "hospitality" },
  { kind: "lever", token: "bluebottlecoffee", name: "Blue Bottle Coffee", pack: "hospitality" },
  { kind: "smartrecruiters", token: "deliveryhero", name: "Delivery Hero", pack: "hospitality" },
  { kind: "smartrecruiters", token: "dominos", name: "Domino's", pack: "hospitality" },
  { kind: "greenhouse", token: "getyourguide", name: "GetYourGuide", pack: "hospitality" },
  { kind: "lever", token: "gopuff", name: "Gopuff", pack: "hospitality" },
  { kind: "greenhouse", token: "hellofresh", name: "HelloFresh", pack: "hospitality" },
  { kind: "smartrecruiters", token: "omio", name: "Omio", pack: "hospitality" },
  { kind: "greenhouse", token: "opentable", name: "OpenTable", pack: "hospitality" },
  { kind: "smartrecruiters", token: "sodexo", name: "Sodexo", pack: "hospitality" },
  { kind: "greenhouse", token: "sweetgreen", name: "Sweetgreen", pack: "hospitality" },
  { kind: "greenhouse", token: "toast", name: "Toast", pack: "hospitality" },
  { kind: "ashby", token: "trainline", name: "Trainline", pack: "hospitality" },
  { kind: "greenhouse", token: "vacasa", name: "Vacasa", pack: "hospitality" },
  { kind: "greenhouse", token: "wolt", name: "Wolt", pack: "hospitality" },

  // Media & Creator (23)
  { kind: "greenhouse", token: "a24", name: "A24", pack: "media" },
  { kind: "greenhouse", token: "axios", name: "Axios", pack: "media" },
  { kind: "smartrecruiters", token: "believe", name: "Believe", pack: "media" },
  { kind: "greenhouse", token: "bungie", name: "Bungie", pack: "media" },
  { kind: "greenhouse", token: "insider", name: "Business Insider", pack: "media" },
  { kind: "greenhouse", token: "buzzfeed", name: "BuzzFeed", pack: "media" },
  { kind: "smartrecruiters", token: "cdprojektred", name: "CD PROJEKT RED", pack: "media" },
  { kind: "recruitee", token: "framestore", name: "Framestore", pack: "media" },
  { kind: "workable", token: "futureplc", name: "Future plc", pack: "media" },
  { kind: "greenhouse", token: "geniussports", name: "Genius Sports", pack: "media" },
  { kind: "smartrecruiters", token: "iheartmedia", name: "iHeartMedia", pack: "media" },
  { kind: "recruitee", token: "mclaren", name: "McLaren", pack: "media" },
  { kind: "ashby", token: "patreon", name: "Patreon", pack: "media" },
  { kind: "smartrecruiters", token: "reachplc", name: "Reach plc", pack: "media" },
  { kind: "greenhouse", token: "scopely", name: "Scopely", pack: "media" },
  { kind: "greenhouse", token: "seatgeek", name: "SeatGeek", pack: "media" },
  { kind: "lever", token: "skydance", name: "Skydance", pack: "media" },
  { kind: "greenhouse", token: "sphereentertainment", name: "Sphere Entertainment", pack: "media" },
  { kind: "smartrecruiters", token: "sportradar", name: "Sportradar", pack: "media" },
  { kind: "ashby", token: "substack", name: "Substack", pack: "media" },
  { kind: "ashby", token: "supercell", name: "Supercell", pack: "media" },
  { kind: "greenhouse", token: "voxmedia", name: "Vox Media", pack: "media" },
  { kind: "greenhouse", token: "zwift", name: "Zwift", pack: "media" },

  // Marketing & Growth (19)
  { kind: "lever", token: "activecampaign", name: "ActiveCampaign", pack: "marketing" },
  { kind: "greenhouse", token: "brandwatch", name: "Brandwatch", pack: "marketing" },
  { kind: "greenhouse", token: "braze", name: "Braze", pack: "marketing" },
  { kind: "lever", token: "brevo", name: "Brevo", pack: "marketing" },
  { kind: "ashby", token: "buffer", name: "Buffer", pack: "marketing" },
  { kind: "ashby", token: "bynder", name: "Bynder", pack: "marketing" },
  { kind: "greenhouse", token: "contentful", name: "Contentful", pack: "marketing" },
  { kind: "lever", token: "contentsquare", name: "Contentsquare", pack: "marketing" },
  { kind: "greenhouse", token: "customerio", name: "Customer.io", pack: "marketing" },
  { kind: "greenhouse", token: "hootsuite", name: "Hootsuite", pack: "marketing" },
  { kind: "greenhouse", token: "klaviyo", name: "Klaviyo", pack: "marketing" },
  { kind: "greenhouse", token: "later", name: "Later", pack: "marketing" },
  { kind: "greenhouse", token: "ogilvy", name: "Ogilvy", pack: "marketing" },
  { kind: "greenhouse", token: "similarweb", name: "Similarweb", pack: "marketing" },
  { kind: "greenhouse", token: "sproutsocial", name: "Sprout Social", pack: "marketing" },
  { kind: "greenhouse", token: "storyblok", name: "Storyblok", pack: "marketing" },
  { kind: "greenhouse", token: "typeform", name: "Typeform", pack: "marketing" },
  { kind: "greenhouse", token: "wk", name: "Wieden+Kennedy", pack: "marketing" },
  { kind: "greenhouse", token: "yotpo", name: "Yotpo", pack: "marketing" },

  // Real Estate & Property (18)
  { kind: "smartrecruiters", token: "colliers", name: "Colliers", pack: "realestate" },
  { kind: "smartrecruiters", token: "crowdstreet", name: "CrowdStreet", pack: "realestate" },
  { kind: "greenhouse", token: "dealpath", name: "Dealpath", pack: "realestate" },
  { kind: "ashby", token: "eliseai", name: "EliseAI", pack: "realestate" },
  { kind: "lever", token: "entrata", name: "Entrata", pack: "realestate" },
  { kind: "lever", token: "fundrise", name: "Fundrise", pack: "realestate" },
  { kind: "greenhouse", token: "homelight", name: "HomeLight", pack: "realestate" },
  { kind: "greenhouse", token: "homeward", name: "Homeward", pack: "realestate" },
  { kind: "greenhouse", token: "immoscout24", name: "ImmoScout24", pack: "realestate" },
  { kind: "greenhouse", token: "kasa", name: "Kasa Living", pack: "realestate" },
  { kind: "greenhouse", token: "orchard", name: "Orchard", pack: "realestate" },
  { kind: "greenhouse", token: "pacaso", name: "Pacaso", pack: "realestate" },
  { kind: "lever", token: "placemakr", name: "Placemakr", pack: "realestate" },
  { kind: "greenhouse", token: "roofstock", name: "Roofstock", pack: "realestate" },
  { kind: "lever", token: "sideinc", name: "Side", pack: "realestate" },
  { kind: "greenhouse", token: "smartrent", name: "SmartRent", pack: "realestate" },
  { kind: "greenhouse", token: "vts", name: "VTS", pack: "realestate" },
  { kind: "greenhouse", token: "wunderflats", name: "Wunderflats", pack: "realestate" },

  // Architecture & Construction (16)
  { kind: "greenhouse", token: "buildops", name: "BuildOps", pack: "aec" },
  { kind: "greenhouse", token: "cannondesign", name: "CannonDesign", pack: "aec" },
  { kind: "greenhouse", token: "dlrgroup", name: "DLR Group", pack: "aec" },
  { kind: "lever", token: "doxel", name: "Doxel", pack: "aec" },
  { kind: "recruitee", token: "duravermeer", name: "Dura Vermeer", pack: "aec" },
  { kind: "greenhouse", token: "fictiv", name: "Fictiv", pack: "aec" },
  { kind: "greenhouse", token: "fieldwire", name: "Fieldwire", pack: "aec" },
  { kind: "ashby", token: "higharc", name: "Higharc", pack: "aec" },
  { kind: "ashby", token: "monumental", name: "Monumental", pack: "aec" },
  { kind: "recruitee", token: "mvrdv", name: "MVRDV", pack: "aec" },
  { kind: "smartrecruiters", token: "ncc", name: "NCC", pack: "aec" },
  { kind: "greenhouse", token: "openspace", name: "OpenSpace", pack: "aec" },
  { kind: "smartrecruiters", token: "ryderarchitecture", name: "Ryder Architecture", pack: "aec" },
  { kind: "smartrecruiters", token: "saintgobain", name: "Saint-Gobain", pack: "aec" },
  { kind: "ashby", token: "speckle", name: "Speckle", pack: "aec" },
  { kind: "recruitee", token: "unstudio", name: "UNStudio", pack: "aec" },

  // Industrial & Manufacturing (19)
  { kind: "lever", token: "ambirobotics", name: "Ambi Robotics", pack: "industrial" },
  { kind: "greenhouse", token: "augury", name: "Augury", pack: "industrial" },
  { kind: "smartrecruiters", token: "averydennison", name: "Avery Dennison", pack: "industrial" },
  { kind: "lever", token: "brightmachines", name: "Bright Machines", pack: "industrial" },
  { kind: "greenhouse", token: "cognite", name: "Cognite", pack: "industrial" },
  { kind: "smartrecruiters", token: "continental", name: "Continental", pack: "industrial" },
  { kind: "lever", token: "dexterity", name: "Dexterity", pack: "industrial" },
  { kind: "greenhouse", token: "divergent", name: "Divergent", pack: "industrial" },
  { kind: "greenhouse", token: "flexport", name: "Flexport", pack: "industrial" },
  { kind: "greenhouse", token: "formic", name: "Formic", pack: "industrial" },
  { kind: "ashby", token: "forto", name: "Forto", pack: "industrial" },
  { kind: "smartrecruiters", token: "konecranes", name: "Konecranes", pack: "industrial" },
  { kind: "lever", token: "osaro", name: "Osaro", pack: "industrial" },
  { kind: "greenhouse", token: "project44", name: "project44", pack: "industrial" },
  { kind: "lever", token: "protolabs", name: "Protolabs", pack: "industrial" },
  { kind: "greenhouse", token: "seurat", name: "Seurat Technologies", pack: "industrial" },
  { kind: "greenhouse", token: "tulip", name: "Tulip Interfaces", pack: "industrial" },
  { kind: "greenhouse", token: "verkada", name: "Verkada", pack: "industrial" },
  { kind: "greenhouse", token: "xometry", name: "Xometry", pack: "industrial" },

  // Hardware & Robotics (23)
  { kind: "greenhouse", token: "agilityrobotics", name: "Agility Robotics", pack: "hardware" },
  { kind: "greenhouse", token: "apptronik", name: "Apptronik", pack: "hardware" },
  { kind: "greenhouse", token: "formlabs", name: "Formlabs", pack: "hardware" },
  { kind: "greenhouse", token: "ionq", name: "IonQ", pack: "hardware" },
  { kind: "greenhouse", token: "lightmatter", name: "Lightmatter", pack: "hardware" },
  { kind: "greenhouse", token: "locusrobotics", name: "Locus Robotics", pack: "hardware" },
  { kind: "greenhouse", token: "lucidmotors", name: "Lucid Motors", pack: "hardware" },
  { kind: "greenhouse", token: "markforged", name: "Markforged", pack: "hardware" },
  { kind: "greenhouse", token: "motional", name: "Motional", pack: "hardware" },
  { kind: "greenhouse", token: "nuro", name: "Nuro", pack: "hardware" },
  { kind: "greenhouse", token: "oura", name: "Oura", pack: "hardware" },
  { kind: "greenhouse", token: "pathrobotics", name: "Path Robotics", pack: "hardware" },
  { kind: "greenhouse", token: "peakdesign", name: "Peak Design", pack: "hardware" },
  { kind: "greenhouse", token: "psiquantum", name: "PsiQuantum", pack: "hardware" },
  { kind: "greenhouse", token: "relativity", name: "Relativity Space", pack: "hardware" },
  { kind: "lever", token: "rigetti", name: "Rigetti", pack: "hardware" },
  { kind: "greenhouse", token: "sambanovasystems", name: "SambaNova", pack: "hardware" },
  { kind: "greenhouse", token: "spacex", name: "SpaceX", pack: "hardware" },
  { kind: "lever", token: "velo3d", name: "Velo3D", pack: "hardware" },
  { kind: "greenhouse", token: "waymo", name: "Waymo", pack: "hardware" },
  { kind: "greenhouse", token: "wayve", name: "Wayve", pack: "hardware" },
  { kind: "ashby", token: "whoop", name: "Whoop", pack: "hardware" },
  { kind: "lever", token: "zoox", name: "Zoox", pack: "hardware" },

  // Climate & Energy (17)
  { kind: "greenhouse", token: "antora", name: "Antora Energy", pack: "climate" },
  { kind: "lever", token: "arcadia", name: "Arcadia", pack: "climate" },
  { kind: "ashby", token: "aurorasolar", name: "Aurora Solar", pack: "climate" },
  { kind: "greenhouse", token: "chargepoint", name: "ChargePoint", pack: "climate" },
  { kind: "lever", token: "charmindustrial", name: "Charm Industrial", pack: "climate" },
  { kind: "recruitee", token: "climeworks", name: "Climeworks", pack: "climate" },
  { kind: "greenhouse", token: "eh2", name: "Electric Hydrogen", pack: "climate" },
  { kind: "ashby", token: "enpal", name: "Enpal", pack: "climate" },
  { kind: "ashby", token: "formenergy", name: "Form Energy", pack: "climate" },
  { kind: "greenhouse", token: "ohme", name: "Ohme", pack: "climate" },
  { kind: "greenhouse", token: "oklo", name: "Oklo", pack: "climate" },
  { kind: "recruitee", token: "otovo", name: "Otovo", pack: "climate" },
  { kind: "greenhouse", token: "redwoodmaterials", name: "Redwood Materials", pack: "climate" },
  { kind: "greenhouse", token: "rondoenergy", name: "Rondo Energy", pack: "climate" },
  { kind: "greenhouse", token: "silananotechnologies", name: "Sila", pack: "climate" },
  { kind: "lever", token: "voltus", name: "Voltus", pack: "climate" },
  { kind: "ashby", token: "watershed", name: "Watershed", pack: "climate" },

  // Professional Services (15)
  { kind: "lever", token: "15five", name: "15Five", pack: "professional" },
  { kind: "ashby", token: "ashby", name: "Ashby", pack: "professional" },
  { kind: "greenhouse", token: "axiom", name: "Axiom Law", pack: "professional" },
  { kind: "greenhouse", token: "cultureamp", name: "Culture Amp", pack: "professional" },
  { kind: "greenhouse", token: "everlaw", name: "Everlaw", pack: "professional" },
  { kind: "greenhouse", token: "greenhouse", name: "Greenhouse Software", pack: "professional" },
  { kind: "ashby", token: "juro", name: "Juro", pack: "professional" },
  { kind: "greenhouse", token: "justworks", name: "Justworks", pack: "professional" },
  { kind: "greenhouse", token: "lattice", name: "Lattice", pack: "professional" },
  { kind: "greenhouse", token: "remotecom", name: "Remote", pack: "professional" },
  { kind: "greenhouse", token: "rocketlawyer", name: "Rocket Lawyer", pack: "professional" },
  { kind: "smartrecruiters", token: "smartrecruiters", name: "SmartRecruiters", pack: "professional" },
  { kind: "greenhouse", token: "thoughtworks", name: "Thoughtworks", pack: "professional" },
  { kind: "greenhouse", token: "valtech", name: "Valtech", pack: "professional" },
  { kind: "smartrecruiters", token: "wtw", name: "Willis Towers Watson", pack: "professional" },
];

/** Materialize the catalog as `Source` records. Nothing is enabled until the user picks a
 *  group, so a first run never fires every request at once. */
export function catalogSources(): Source[] {
  return CATALOG.map((row) => ({
    id: `${row.kind}:${row.token}`,
    kind: row.kind,
    token: row.token,
    name: row.name,
    pack: row.pack,
    enabled: false,
  }));
}

export function packLabel(id: string): string {
  return PACKS.find((p) => p.id === id)?.label ?? "Added by you";
}
